In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
import seaborn as sns
sns.set(style="white") #white background style for seaborn plots
sns.set(style="whitegrid", color_codes=True)

C:\Users\budde\AppData\Local\Temp\ipykernel_5280\3810981710.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [19]:
baseball_df = pd.read_csv('data/Merged_Data.csv')
baseball_df

join team_id opponent_id league opponent_league division  \
0      3/30/2023 DH0 AZ      AZ         LAD     NL              NL        W   
1     3/30/2023 DH0 ATL     ATL         WSH     NL              NL        E   
2     3/30/2023 DH0 BAL     BAL         BOS     AL              AL        E   
3     3/30/2023 DH0 BOS     BOS         BAL     AL              AL        E   
4     3/30/2023 DH0 CHC     CHC         MIL     NL              NL        C   
...                 ...     ...         ...    ...             ...      ...   
4855  10/1/2023 DH0 STL     STL         CIN     NL              NL        C   
4856   10/1/2023 DH0 TB      TB         TOR     AL              AL        E   
4857  10/1/2023 DH0 TEX     TEX         SEA     AL              AL        W   
4858  10/1/2023 DH0 TOR     TOR          TB     AL              AL        E   
4859  10/1/2023 DH0 WSH     WSH         ATL     NL              NL        E   

     opponent_division team_side       date           start_time  ...  \
0                    W      Away  3/30/2023  2023-03-30 19:10:00  ...   
1                    E      Away  3/30/2023  2023-03-30 13:05:00  ...   
2                    E      Away  3/30/2023  2023-03-30 14:10:00  ...   
3                    E      Home  3/30/2023  2023-03-30 14:10:00  ...   
4                    C      Home  3/30/2023  2023-03-30 13:20:00  ...   
...                ...       ...        ...                  ...  ...   
4855                 C      Home  10/1/2023  2023-10-01 14:15:00  ...   
4856                 E      Away  10/1/2023  2023-10-01 15:07:00  ...   
4857                 W      Away  10/1/2023  2023-10-01 12:10:00  ...   
4858                 E      Home  10/1/2023  2023-10-01 15:07:00  ...   
4859                 E      Away  10/1/2023  2023-10-01 15:10:00  ...   

      pos8_int_start_distance pos9_int_start_distance pitcher_run_exp run_exp  \
0                         323                     290            -3.7     3.7   
1                         323                     299             3.8    -3.8   
2                         325                     305            -2.4     2.4   
3                         324                     302            -5.5     5.5   
4                         320                     296             4.9    -4.9   
...                       ...                     ...             ...     ...   
4855                      322                     307             1.7    -1.7   
4856                      318                     289            -3.1     3.1   
4857                      315                     292             3.8    -3.8   
4858                      313                     281            -5.9     5.9   
4859                      324                     299            -4.4     4.4   

     Day of week Away score Home score  Attendance  Duration (min)  Score Line  
0            Thu          2          8       52075             155   110000000  
1            Thu          7          2       35756             187   030100003  
2            Thu         10          9       36049             190   100430200  
3            Thu         10          9       36049             190   100102032  
4            Thu          0          4       36054             141   00400000x  
...          ...        ...        ...         ...             ...         ...  
4855         Sun          3          4       44614             136   01300000x  
4856         Sun         12          8       42058             167   170111100  
4857         Sun          0          1       43997             121   000000000  
4858         Sun         12          8       42058             167   030003110  
4859         Sun         10          9       40697             189   410000023  

[4860 rows x 59 columns]

In [24]:
columns_list = baseball_df.columns.tolist()

print("Columns of the baseball_df dataframe:")
for column in columns_list:
    print(column)

Columns of the baseball_df dataframe:
join
team_id
opponent_id
league
opponent_league
division
opponent_division
team_side
date
start_time
doubleheader
time_of_day
sky
field_condition
precipitation
wind_direction
park_id
temperature_fahrenheit
attendance
wind_speed_mph
series_id
season_game_number
series_game_number
days_since_last_game
pitches
ba
iso
babip
slg
woba
xwoba
xba
hits
abs
launch_speed
launch_angle
spin_rate
velocity
effective_speed
whiffs
swings
takes
eff_min_vel
release_extension
pos3_int_start_distance
pos4_int_start_distance
pos5_int_start_distance
pos6_int_start_distance
pos7_int_start_distance
pos8_int_start_distance
pos9_int_start_distance
pitcher_run_exp
run_exp
Day of week
Away score
Home score
Attendance
Duration (min)
Score Line


In [26]:
baseball_df['Home Team Win'] = (baseball_df['Home score'] - baseball_df['Away score']) > 0
baseball_df['Home Team Win'] = baseball_df['Home Team Win'].astype(int)
baseball_df[['Home Team Win']]

Home Team Win
0                 1
1                 0
2                 0
3                 0
4                 1
...             ...
4855              1
4856              0
4857              1
4858              0
4859              0

[4860 rows x 1 columns]

In [28]:
#Splitting the data into a training set and a testing set
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(baseball_df, test_size=0.2, random_state=42)

In [29]:
x_train = train_set[['Home score']]
y_train = train_set[['Home Team Win']]

x_test = test_set[['Home score']]
y_test = test_set[['Home Team Win']]

In [30]:
y_train_1 = (y_train == 1).to_numpy().ravel()
y_test_1 = (y_test == 1).to_numpy().ravel()

In [31]:
#Binary Classifier looked like the best choice since we are attempting to predict a binary attitude
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(x_train, y_train_1)

SGDClassifier(random_state=42)

In [32]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, x_train, y_train_1, cv=3, scoring="accuracy")

array([0.73996914, 0.7492284 , 0.74382716])

In [33]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, x_train, y_train_1, cv=3)

In [34]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train_1, y_train_pred)
cm

array([[1346,  521],
       [ 473, 1548]], dtype=int64)

In [35]:
#This means that given the Home team's score the model can accurately predict the winner almost 75% of the time
TN, FP, FN, TP = confusion_matrix(y_train_1, y_train_pred).ravel()
accuracy =  (TP + TN) / (TP + FP + TN + FN)

print('Accuracy of the binary classifier = {:0.3f}'.format(accuracy))

Accuracy of the binary classifier = 0.744


In [36]:
#Get a precision score from the predicted values
from sklearn.metrics import precision_score, recall_score

precision_score(y_train_1, y_train_pred) 

0.7481875302078299

In [37]:
#Get a recall score from the predicted values
recall_score(y_train_1, y_train_pred)

0.7659574468085106

In [38]:
#Get the f1 score from the predicted values. Overall the score was pretty okay but could be improved on greatly
from sklearn.metrics import f1_score

f1_score(y_train_1, y_train_pred)

0.7569682151589242

In [47]:
baseball_df[['ba']]

ba
0     0.353
1     0.242
2     0.324
3     0.395
4     0.138
...     ...
4855  0.257
4856  0.300
4857  0.143
4858  0.372
4859  0.289

[4860 rows x 1 columns]

In [48]:
#We will now look attempt to predict the win based on Batting Average
x_train2 = train_set[['ba']]

x_test2 = test_set[['ba']]

In [49]:
cross_val_score(sgd_clf, x_train2, y_train_1, cv=3, scoring="accuracy")

array([0.48070988, 0.52006173, 0.52006173])

In [50]:
y_train_pred2 = cross_val_predict(sgd_clf, x_train2, y_train_1, cv=3)

In [51]:
cm = confusion_matrix(y_train_1, y_train_pred2)
cm

array([[ 623, 1244],
       [ 673, 1348]], dtype=int64)

In [52]:
#Surprisingly the team batting average has very little to do with which team wins
TN2, FP2, FN2, TP2 = confusion_matrix(y_train_1, y_train_pred2).ravel()
accuracy =  (TP2 + TN2) / (TP2 + FP2 + TN2 + FN2)

print('Accuracy of the binary classifier = {:0.3f}'.format(accuracy))

Accuracy of the binary classifier = 0.507


In [53]:
precision_score(y_train_1, y_train_pred2) 

0.5200617283950617

In [54]:
recall_score(y_train_1, y_train_pred2)

0.6669965363681346

In [55]:
f1_score(y_train_1, y_train_pred2)

0.5844352915673098

In [58]:
#Although binary classifiers are a very helpful tool they are also quite limited in what you can do with them since you can only sort items into two
#categories. In this notebook we looked at predicting which team won based on the Home Team's Score and the Batting Average in the game. This is just 
#a starting point as many other models will be more helpful for this dataset