In [54]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
import seaborn as sns
sns.set(style="white") #white background style for seaborn plots
sns.set(style="whitegrid", color_codes=True)

In [55]:
baseball_df = pd.read_csv('data/cleanedFull.csv')
baseball_df

Unnamed: 0         JOIN  doubleheader  temperature_fahrenheit  \
0              0  45015BALDH0             0                      38   
1              1  45015BOSDH0             0                      38   
2              2  45015CHCDH0             0                      42   
3              3  45015MILDH0             0                      42   
4              4  45015CINDH0             0                      61   
...          ...          ...           ...                     ...   
4855        4855   45200SFDH0             0                      64   
4856        4856   45200TBDH0             0                      79   
4857        4857  45200TORDH0             0                      79   
4858        4858  45200ATLDH0             0                      81   
4859        4859  45200WSHDH0             0                      81   

      season_game_number  days_since_last_game  pitches_p   ba_p  iso_p  \
0                      1                   1.0        153  0.324  0.118   
1                      1                   1.0        191  0.395  0.263   
2                      1                   1.0        133  0.138  0.000   
3                      1                   1.0        124  0.200  0.000   
4                      1                   1.0        178  0.200  0.133   
...                  ...                   ...        ...    ...    ...   
4855                 162                   1.0        173  0.206  0.088   
4856                 162                   1.0        155  0.300  0.225   
4857                 162                   1.0        166  0.372  0.302   
4858                 162                   1.0        165  0.385  0.103   
4859                 162                   1.0        167  0.289  0.237   

      babip_p  ...  takes_h  eff_min_vel_h  release_extension_h  \
0       0.407  ...      113           -6.5                 6.65   
1       0.464  ...       81           -2.7                 6.52   
2       0.235  ...       65            0.5                 6.47   
3       0.240  ...       74           -0.3                 5.91   
4       0.263  ...       91            0.2                 6.43   
...       ...  ...      ...            ...                  ...   
4855    0.240  ...       73            0.7                 6.66   
4856    0.344  ...       87            0.2                 6.57   
4857    0.419  ...       79            0.5                 6.82   
4858    0.395  ...       80           -0.2                 6.27   
4859    0.321  ...       83            0.3                 6.55   

      pitcher_run_exp_h  run_exp_h  duration  score  opp_score  opp_ScoreLine  \
0                  -5.5        5.5       190     10          9      100102032   
1                  -2.4        2.4       190      9         10      100430200   
2                   0.6       -0.6       141      4          0      000000000   
3                   4.9       -4.9       141      0          4      00400000x   
4                   0.1       -0.1       182      4          5      001300010   
...                 ...        ...       ...    ...        ...            ...   
4855                2.4       -2.4       164      2          5      000005000   
4856               -5.9        5.9       167     12          8      030003110   
4857               -3.1        3.1       167      8         12      170111100   
4858               -4.4        4.4       189      9         10      410000023   
4859               -4.9        4.9       189     10          9      203000211   

      winLoss_numeric  
0                   1  
1                   0  
2                   1  
3                   0  
4                   0  
...               ...  
4855                0  
4856                1  
4857                0  
4858                0  
4859                1  

[4860 rows x 55 columns]

In [56]:
columns_list = baseball_df.columns.tolist()

print("Columns of the baseball_df dataframe:")
for column in columns_list:
    print(column)

Columns of the baseball_df dataframe:
Unnamed: 0
JOIN
doubleheader
temperature_fahrenheit
season_game_number
days_since_last_game
pitches_p
ba_p
iso_p
babip_p
slg_p
woba_p
xwoba_p
xba_p
hits_p
abs_p
launch_speed_p
launch_angle_p
spin_rate_p
velocity_p
effective_speed_p
whiffs_p
swings_p
takes_p
eff_min_vel_p
release_extension_p
pitcher_run_exp_p
run_exp_p
pitches_h
ba_h
iso_h
babip_h
slg_h
woba_h
xwoba_h
xba_h
hits_h
abs_h
launch_speed_h
launch_angle_h
spin_rate_h
velocity_h
effective_speed_h
whiffs_h
swings_h
takes_h
eff_min_vel_h
release_extension_h
pitcher_run_exp_h
run_exp_h
duration
score
opp_score
opp_ScoreLine
winLoss_numeric


In [ ]:
baseball_df['score-run_exp_p'] = baseball_df['score'] - baseball_df['run_exp_p']

In [ ]:
baseball_df['score-run_exp_p']

In [88]:
baseball_df['score-run_exp_p-woba_p'] = baseball_df['score-run_exp_p'] - baseball_df['woba_p']

In [89]:
#Splitting the data into a training set and a testing set
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(baseball_df, test_size=0.2, random_state=42)

In [90]:
x_train = train_set[['score']]
y_train = train_set[['winLoss_numeric']]

x_test = test_set[['score']]
y_test = test_set[['winLoss_numeric']]

In [91]:
y_train_1 = (y_train == 1).to_numpy().ravel()
y_test_1 = (y_test == 1).to_numpy().ravel()

In [92]:
#Binary Classifier looked like the best choice since we are attempting to predict a binary attitude
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(x_train, y_train_1)

SGDClassifier(random_state=42)

In [93]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, x_train, y_train_1, cv=3, scoring="accuracy")

array([0.76929012, 0.75154321, 0.75308642])

In [94]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, x_train, y_train_1, cv=3)

In [95]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train_1, y_train_pred)
cm

array([[1397,  527],
       [ 414, 1550]], dtype=int64)

In [96]:
#This means that given the Home team's score the model can accurately predict the winner almost 75% of the time
TN, FP, FN, TP = confusion_matrix(y_train_1, y_train_pred).ravel()
accuracy =  (TP + TN) / (TP + FP + TN + FN)

print('Accuracy of the binary classifier = {:0.3f}'.format(accuracy))

Accuracy of the binary classifier = 0.758


In [97]:
#Get a precision score from the predicted values
from sklearn.metrics import precision_score, recall_score

precision_score(y_train_1, y_train_pred) 

0.746268656716418

In [98]:
#Get a recall score from the predicted values
recall_score(y_train_1, y_train_pred)

0.7892057026476579

In [99]:
#Get the f1 score from the predicted values. Overall the score was pretty okay but could be improved on greatly
from sklearn.metrics import f1_score

f1_score(y_train_1, y_train_pred)

0.7671368473150211

In [100]:
#We will now look attempt to predict the win based on runs expected
x_train2 = train_set[['run_exp_p']]

x_test2 = test_set[['run_exp_p']]

In [101]:
cross_val_score(sgd_clf, x_train2, y_train_1, cv=3, scoring="accuracy")

array([0.7492284 , 0.75617284, 0.75308642])

In [102]:
y_train_pred2 = cross_val_predict(sgd_clf, x_train2, y_train_1, cv=3)

In [103]:
cm = confusion_matrix(y_train_1, y_train_pred2)
cm

array([[1330,  594],
       [ 367, 1597]], dtype=int64)

In [104]:
TN2, FP2, FN2, TP2 = confusion_matrix(y_train_1, y_train_pred2).ravel()
accuracy =  (TP2 + TN2) / (TP2 + FP2 + TN2 + FN2)

print('Accuracy of the binary classifier = {:0.3f}'.format(accuracy))

Accuracy of the binary classifier = 0.753


In [105]:
precision_score(y_train_1, y_train_pred2) 

0.72889091738932

In [106]:
recall_score(y_train_1, y_train_pred2)

0.8131364562118126

In [107]:
f1_score(y_train_1, y_train_pred2)

0.7687123947051745

In [108]:
x_train3 = train_set[['score-run_exp_p']]

x_test3 = test_set[['score-run_exp_p']]

In [109]:
y_train_pred3 = cross_val_predict(sgd_clf, x_train3, y_train_1, cv=3)

In [110]:
cm = confusion_matrix(y_train_1, y_train_pred3)
cm

array([[1848,   76],
       [ 106, 1858]], dtype=int64)

In [111]:
TN3, FP3, FN3, TP3 = confusion_matrix(y_train_1, y_train_pred3).ravel()
accuracy =  (TP3 + TN3) / (TP3 + FP3 + TN3 + FN3)

print('Accuracy of the binary classifier = {:0.3f}'.format(accuracy))

Accuracy of the binary classifier = 0.953


In [112]:
precision_score(y_train_1, y_train_pred3) 

0.9607032057911065

In [113]:
recall_score(y_train_1, y_train_pred3)

0.9460285132382892

In [114]:
f1_score(y_train_1, y_train_pred3)

0.9533093894304772